"""
hw_test_generator.py — Hardware Unit Test Scaffold Generator for KiCad AI Copilot
==================================================================================
Reads a design JSON and generates a complete firmware test scaffold including
pin definitions, HAL stubs, Unity test harness, hardware manifest, and CMakeLists.

Usage:
    python hw_test_generator.py --input design.json --framework stm32 --output ./firmware/
"""

import argparse
import json
import os
import sys
from datetime import datetime
from typing import Any

SUPPORTED_FRAMEWORKS = ("stm32", "arduino", "generic")

BANNER = f"// Generated by KiCad AI Copilot hw_test_generator.py on {{ts}}\n// DO NOT EDIT — regenerate from design.json\n"

# ---------------------------------------------------------------------------
# Helper: component type → peripheral category
# ---------------------------------------------------------------------------

def _classify(comp: dict) -> str:
    t = comp.get("type", "").upper()
    name = comp.get("name", "").upper()
    combined = t + " " + name
    if any(k in combined for k in ("MCU", "STM32", "ATMEGA", "MICROCONTROLLER")):
        return "MCU"
    if "LED" in combined:
        return "LED"
    if "SPI" in combined or "FLASH" in combined:
        return "SPI"
    if "I2C" in combined or "EEPROM" in combined or "IMU" in combined:
        return "I2C"
    if "BUTTON" in combined or "BTN" in combined or "SWITCH" in combined:
        return "BUTTON"
    if "POWER" in combined or "LDO" in combined or "VREG" in combined or "REG" in combined:
        return "POWER"
    if "UART" in combined or "SERIAL" in combined:
        return "UART"
    if "PWM" in combined or "MOTOR" in combined:
        return "PWM"
    return "GENERIC"


def _safe_name(label: str) -> str:
    """Convert an arbitrary string to a valid C identifier."""
    return "".join(c if c.isalnum() or c == "_" else "_" for c in label).upper()


# ---------------------------------------------------------------------------
# File generators
# ---------------------------------------------------------------------------

def _gen_pins_h(components: list[dict], framework: str) -> str:
    ts = datetime.now().isoformat(timespec="seconds")
    lines = [
        BANNER.format(ts=ts),
        "#pragma once",
        "#ifndef PINS_H",
        "#define PINS_H",
        "",
        "// ── Pin / Net Definitions ─────────────────────────────────────────",
    ]

    if framework == "stm32":
        gpio_prefix = "P"
        ports = "ABCDEFGH"
        _port_idx = 0
        _pin_idx  = 0

        def next_pin() -> str:
            nonlocal _port_idx, _pin_idx
            pin = f"{gpio_prefix}{ports[_port_idx % len(ports)]}{_pin_idx}"
            _pin_idx += 1
            if _pin_idx > 15:
                _pin_idx = 0
                _port_idx += 1
            return pin

    elif framework == "arduino":
        _pin_counter = [2]

        def next_pin() -> str:  # type: ignore[misc]
            p = str(_pin_counter[0])
            _pin_counter[0] += 1
            return p
    else:
        _pin_counter = [0]

        def next_pin() -> str:  # type: ignore[misc]
            p = f"GPIO_{_pin_counter[0]}"
            _pin_counter[0] += 1
            return p

    for comp in components:
        ref   = _safe_name(comp.get("ref", comp.get("id", "UNKNOWN")))
        ctype = _classify(comp)
        nets  = comp.get("nets", {})
        lines.append(f"")
        lines.append(f"// {comp.get('ref', comp.get('id', '?'))} — {ctype}")
        if nets:
            for net_name, net_val in nets.items():
                macro = f"PIN_{ref}_{_safe_name(net_name)}"
                value = net_val if net_val else next_pin()
                lines.append(f"#define {macro:<40s} {value}")
        else:
            # Auto-assign generic pins
            for pin_label in _default_pins_for(ctype):
                macro = f"PIN_{ref}_{_safe_name(pin_label)}"
                lines.append(f"#define {macro:<40s} {next_pin()}")

    lines += ["", "#endif // PINS_H", ""]
    return "\n".join(lines)


def _default_pins_for(ctype: str) -> list[str]:
    return {
        "MCU":     ["RESET", "BOOT0"],
        "LED":     ["ANODE"],
        "SPI":     ["CS", "SCK", "MOSI", "MISO"],
        "I2C":     ["SDA", "SCL"],
        "BUTTON":  ["IN"],
        "POWER":   ["EN", "PG"],
        "UART":    ["TX", "RX"],
        "PWM":     ["OUT"],
        "GENERIC": ["IO"],
    }.get(ctype, ["IO"])


def _gen_hal_stubs_h(components: list[dict]) -> str:
    ts = datetime.now().isoformat(timespec="seconds")
    seen: set[str] = set()
    protos: list[str] = []

    for comp in components:
        ctype = _classify(comp)
        if ctype in seen:
            continue
        seen.add(ctype)
        protos += _hal_protos(ctype)

    lines = [
        BANNER.format(ts=ts),
        "#pragma once",
        "#ifndef HAL_STUBS_H",
        "#define HAL_STUBS_H",
        "",
        "#include <stdint.h>",
        "",
        "// ── HAL Stub Declarations ─────────────────────────────────────────",
        "",
    ]
    for p in protos:
        lines.append(f"{p};")
    lines += ["", "#endif // HAL_STUBS_H", ""]
    return "\n".join(lines)


def _hal_protos(ctype: str) -> list[str]:
    return {
        "MCU":     ["void MCU_Init(void)", "void MCU_Reset(void)"],
        "LED":     ["void LED_Set(uint8_t state)", "void LED_Toggle(void)"],
        "SPI":     ["void SPI_Init(void)",
                    "int  SPI_Transfer(uint8_t *tx, uint8_t *rx, uint16_t len)"],
        "I2C":     ["void I2C_Init(void)",
                    "int  I2C_Write(uint8_t addr, uint8_t *data, uint16_t len)",
                    "int  I2C_Read(uint8_t addr, uint8_t *data, uint16_t len)"],
        "BUTTON":  ["uint8_t BUTTON_Read(void)"],
        "POWER":   ["void    POWER_Init(void)", "float   POWER_GetVoltage(void)"],
        "UART":    ["void UART_Init(uint32_t baud)",
                    "void UART_Send(uint8_t *data, uint16_t len)"],
        "PWM":     ["void PWM_Init(void)", "void PWM_SetDuty(uint8_t duty_pct)"],
        "GENERIC": ["void GENERIC_Init(void)"],
    }.get(ctype, ["void GENERIC_Init(void)"])


def _gen_hal_stubs_c(components: list[dict]) -> str:
    ts = datetime.now().isoformat(timespec="seconds")
    seen: set[str] = set()
    impls: list[str] = []

    for comp in components:
        ctype = _classify(comp)
        if ctype in seen:
            continue
        seen.add(ctype)
        impls += _hal_impls(ctype)

    lines = [
        BANNER.format(ts=ts),
        '#include "hal_stubs.h"',
        '#include "pins.h"',
        "",
        "// ── HAL Stub Implementations ──────────────────────────────────────",
        "",
    ]
    lines += impls
    return "\n".join(lines)


def _hal_impls(ctype: str) -> list[str]:
    templates: dict[str, list[str]] = {
        "MCU": [
            "void MCU_Init(void) {",
            "    /* Initialise system clocks, peripherals */",
            "}",
            "",
            "void MCU_Reset(void) {",
            "    /* Trigger software reset — implement with NVIC_SystemReset() */",
            "}",
            "",
        ],
        "LED": [
            "void LED_Set(uint8_t state) {",
            "    /* Write state to LED GPIO */",
            "    (void)state;",
            "}",
            "",
            "void LED_Toggle(void) {",
            "    /* Toggle LED GPIO */",
            "}",
            "",
        ],
        "SPI": [
            "void SPI_Init(void) {",
            "    /* Configure SPI peripheral */",
            "}",
            "",
            "int SPI_Transfer(uint8_t *tx, uint8_t *rx, uint16_t len) {",
            "    /* Full-duplex SPI transfer stub */",
            "    (void)tx; (void)rx; (void)len;",
            "    return 0;",
            "}",
            "",
        ],
        "I2C": [
            "void I2C_Init(void) {",
            "    /* Configure I2C peripheral */",
            "}",
            "",
            "int I2C_Write(uint8_t addr, uint8_t *data, uint16_t len) {",
            "    (void)addr; (void)data; (void)len;",
            "    return 0;",
            "}",
            "",
            "int I2C_Read(uint8_t addr, uint8_t *data, uint16_t len) {",
            "    (void)addr; (void)data; (void)len;",
            "    return 0;",
            "}",
            "",
        ],
        "BUTTON": [
            "uint8_t BUTTON_Read(void) {",
            "    /* Return current button state (1 = pressed) */",
            "    return 0;",
            "}",
            "",
        ],
        "POWER": [
            "void POWER_Init(void) {",
            "    /* Enable power rail, wait for PG */",
            "}",
            "",
            "float POWER_GetVoltage(void) {",
            "    /* Read ADC and convert to volts */",
            "    return 3.3f;",
            "}",
            "",
        ],
        "UART": [
            "void UART_Init(uint32_t baud) {",
            "    (void)baud;",
            "}",
            "",
            "void UART_Send(uint8_t *data, uint16_t len) {",
            "    (void)data; (void)len;",
            "}",
            "",
        ],
        "PWM": [
            "void PWM_Init(void) {",
            "    /* Configure timer for PWM output */",
            "}",
            "",
            "void PWM_SetDuty(uint8_t duty_pct) {",
            "    (void)duty_pct;",
            "}",
            "",
        ],
        "GENERIC": [
            "void GENERIC_Init(void) {",
            "    /* Generic peripheral init */",
            "}",
            "",
        ],
    }
    return templates.get(ctype, templates["GENERIC"])


def _gen_test_harness_c(components: list[dict]) -> str:
    ts = datetime.now().isoformat(timespec="seconds")
    seen: set[str] = set()
    test_fns: list[str] = []
    run_tests: list[str] = []

    for comp in components:
        ctype = _classify(comp)
        fn_name = f"test_{ctype}"
        if fn_name in seen:
            # Give each component its own labelled test
            ref_safe = _safe_name(comp.get("ref", comp.get("id", "X")))
            fn_name = f"test_{ctype}_{ref_safe}"
        seen.add(fn_name)
        test_fns.append(_unity_test_fn(fn_name, ctype, comp))
        run_tests.append(f"    RUN_TEST({fn_name});")

    lines = [
        BANNER.format(ts=ts),
        "#include <unity.h>",
        '#include "hal_stubs.h"',
        '#include "pins.h"',
        "",
        "// ── Unity Test Harness ────────────────────────────────────────────",
        "",
        "void setUp(void) {",
        "    /* Called before each test — reset peripherals */",
        "    MCU_Init();",
        "}",
        "",
        "void tearDown(void) {",
        "    /* Called after each test — cleanup */",
        "}",
        "",
    ]
    for fn in test_fns:
        lines += fn.splitlines()
        lines.append("")

    lines += [
        "int main(void) {",
        "    UNITY_BEGIN();",
    ]
    lines += run_tests
    lines += [
        "    return UNITY_END();",
        "}",
        "",
    ]
    return "\n".join(lines)


def _unity_test_fn(fn_name: str, ctype: str, comp: dict) -> str:
    ref = comp.get("ref", comp.get("id", "?"))
    bodies: dict[str, str] = {
        "MCU":     f"    MCU_Init();\n    TEST_PASS_MESSAGE(\"MCU ({ref}) init OK\");",
        "LED":     f"    LED_Set(1);\n    LED_Toggle();\n    TEST_PASS_MESSAGE(\"LED ({ref}) toggle OK\");",
        "SPI":     f"    uint8_t tx[4] = {{0xDE, 0xAD, 0xBE, 0xEF}};\n    uint8_t rx[4] = {{0}};\n"
                   f"    int r = SPI_Transfer(tx, rx, 4);\n    TEST_ASSERT_EQUAL_INT(0, r);",
        "I2C":     f"    uint8_t buf[2] = {{0x00, 0x01}};\n    int r = I2C_Write(0x50, buf, 2);\n    TEST_ASSERT_EQUAL_INT(0, r);",
        "BUTTON":  f"    uint8_t s = BUTTON_Read();\n    TEST_ASSERT_TRUE(s == 0 || s == 1);",
        "POWER":   f"    POWER_Init();\n    float v = POWER_GetVoltage();\n    TEST_ASSERT_FLOAT_WITHIN(0.5f, 3.3f, v);",
        "UART":    f"    UART_Init(115200);\n    uint8_t msg[] = \"ping\";\n    UART_Send(msg, 4);\n    TEST_PASS();",
        "PWM":     f"    PWM_Init();\n    PWM_SetDuty(50);\n    TEST_PASS_MESSAGE(\"PWM ({ref}) duty 50%% OK\");",
    }
    body = bodies.get(ctype, f"    TEST_PASS_MESSAGE(\"Generic test for {ref}\");")
    return f"void {fn_name}(void) {{\n{body}\n}}"


def _gen_hardware_yaml(components: list[dict], project_name: str) -> str:
    ts = datetime.now().isoformat(timespec="seconds")
    lines = [
        f"# hardware.yaml — Hardware Manifest",
        f"# Generated: {ts}",
        f"",
        f"project_name: \"{project_name}\"",
        f"",
        f"components:",
    ]
    for comp in components:
        ref   = comp.get("ref", comp.get("id", "?"))
        ctype = _classify(comp)
        nets  = comp.get("nets", {})
        lines.append(f"  - ref: \"{ref}\"")
        lines.append(f"    type: \"{ctype}\"")
        if nets:
            lines.append(f"    nets:")
            for k, v in nets.items():
                lines.append(f"      {k}: \"{v}\"")
    lines += [
        "",
        "test_targets:",
    ]
    seen: set[str] = set()
    for comp in components:
        ctype = _classify(comp)
        if ctype not in seen:
            lines.append(f"  - {ctype}")
            seen.add(ctype)
    lines.append("")
    return "\n".join(lines)


def _gen_cmake(project_name: str) -> str:
    ts = datetime.now().isoformat(timespec="seconds")
    return f"""\
# CMakeLists.txt — Generated by KiCad AI Copilot on {ts}
cmake_minimum_required(VERSION 3.16)
project({project_name}_tests C)

set(CMAKE_C_STANDARD 11)

# Unity test framework (fetch from GitHub or provide locally)
include(FetchContent)
FetchContent_Declare(
  unity
  GIT_REPOSITORY https://github.com/ThrowTheSwitch/Unity.git
  GIT_TAG        v2.5.2
)
FetchContent_MakeAvailable(unity)

add_executable({project_name}_tests
    test_harness.c
    hal_stubs.c
)

target_include_directories({project_name}_tests PRIVATE
    ${{CMAKE_CURRENT_SOURCE_DIR}}
    ${{unity_SOURCE_DIR}}/src
)

target_link_libraries({project_name}_tests PRIVATE unity)

enable_testing()
add_test(NAME {project_name}_hw_tests COMMAND {project_name}_tests)
"""


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def generate_firmware_stubs(design: dict, framework: str) -> dict:
    """
    Generate all firmware test scaffold files from a design dict.

    Parameters
    ----------
    design    : dict  — design JSON with `components` list
    framework : str   — stm32 | arduino | generic

    Returns
    -------
    dict with keys: pins_h, hal_stubs_c, hal_stubs_h, test_harness_c,
                    hardware_yaml, cmake_txt
    """
    if framework not in SUPPORTED_FRAMEWORKS:
        raise ValueError(f"Unsupported framework '{framework}'. Choose from: {SUPPORTED_FRAMEWORKS}")

    components   = design.get("components", [])
    project_name = design.get("project_name", "kicad_project")

    return {
        "pins_h":        _gen_pins_h(components, framework),
        "hal_stubs_h":   _gen_hal_stubs_h(components),
        "hal_stubs_c":   _gen_hal_stubs_c(components),
        "test_harness_c": _gen_test_harness_c(components),
        "hardware_yaml": _gen_hardware_yaml(components, project_name),
        "cmake_txt":     _gen_cmake(project_name),
    }


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main() -> None:
    parser = argparse.ArgumentParser(
        description="KiCad AI Copilot — Hardware Test Scaffold Generator",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )
    parser.add_argument("--input",     required=True, help="Design JSON file")
    parser.add_argument("--framework", required=True, choices=SUPPORTED_FRAMEWORKS,
                        help="Target firmware framework")
    parser.add_argument("--output",    required=True, help="Output directory for generated files")
    args = parser.parse_args()

    if not os.path.isfile(args.input):
        print(f"ERROR: input file '{args.input}' not found.", file=sys.stderr)
        sys.exit(1)

    with open(args.input, encoding="utf-8") as fh:
        design = json.load(fh)

    os.makedirs(args.output, exist_ok=True)

    stubs = generate_firmware_stubs(design, args.framework)

    file_map = {
        "pins.h":          stubs["pins_h"],
        "hal_stubs.h":     stubs["hal_stubs_h"],
        "hal_stubs.c":     stubs["hal_stubs_c"],
        "test_harness.c":  stubs["test_harness_c"],
        "hardware.yaml":   stubs["hardware_yaml"],
        "CMakeLists.txt":  stubs["cmake_txt"],
    }

    print(f"[HW Test Generator] Generating {len(file_map)} files into '{args.output}' …")
    for filename, content in file_map.items():
        dest = os.path.join(args.output, filename)
        with open(dest, "w", encoding="utf-8") as fh:
            fh.write(content)
        print(f"  ✔  {filename}")

    print(f"[HW Test Generator] Done — framework: {args.framework}.")


if __name__ == "__main__":
    main()
