"""
KiCad AI Copilot — Action Plugin (KiCad 7, 8, 9)
==================================================
Uses the pcbnew ActionPlugin API (SWIG-based).
Note: SWIG pcbnew is deprecated in KiCad 9 and will be removed in KiCad 11.
For KiCad 10+, see plugin_ipc.py instead.

This plugin:
  1. Shows a dialog to browse for the AI Copilot JSON file
  2. Imports components as footprint stubs into the active PCB
  3. Adds net declarations and placement notes
  4. Opens the web UI if requested
"""

import os
import sys
import json
import webbrowser
from pathlib import Path

try:
    import pcbnew
    import wx
    HAS_KICAD = True
except ImportError:
    HAS_KICAD = False
    print("[KiCad AI Copilot] pcbnew not available — standalone mode")


# ── Constants ──────────────────────────────────────────────
PLUGIN_DIR = Path(__file__).parent
WEB_UI_PATH = PLUGIN_DIR.parent / "index.html"
ICON_PATH = PLUGIN_DIR / "resources" / "icon.png"

# KiCad unit conversion: 1mm = 1e6 internal units (nm-based in older KiCad)
# KiCad 7+: uses mm directly in most API calls
MM = 1_000_000  # pcbnew.FromMM(1)


# ═══════════════════════════════════════════════════════════
# IMPORT DIALOG
# ═══════════════════════════════════════════════════════════
class CopilotImportDialog(wx.Dialog):
    """
    Dialog for importing AI Copilot JSON into KiCad PCB.
    """
    def __init__(self, parent):
        super().__init__(parent, title="KiCad AI Copilot — Import Design",
                         size=(560, 400), style=wx.DEFAULT_DIALOG_STYLE | wx.RESIZE_BORDER)

        self.json_path = None
        self._build_ui()
        self.Centre()

    def _build_ui(self):
        panel = wx.Panel(self)
        vbox = wx.BoxSizer(wx.VERTICAL)

        # Header
        header = wx.StaticText(panel, label="🔌 KiCad AI Copilot")
        header_font = wx.Font(14, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD)
        header.SetFont(header_font)
        vbox.Add(header, 0, wx.ALL | wx.LEFT, 12)

        sub = wx.StaticText(panel, label="Import a design JSON generated by the KiCad AI Copilot web tool.")
        sub.SetForegroundColour(wx.Colour(100, 100, 100))
        vbox.Add(sub, 0, wx.LEFT | wx.BOTTOM, 12)

        vbox.Add(wx.StaticLine(panel), 0, wx.EXPAND | wx.LEFT | wx.RIGHT, 8)

        # File picker
        file_box = wx.StaticBoxSizer(wx.StaticBox(panel, label="Step 1: Select AI Copilot JSON File"), wx.VERTICAL)

        hbox1 = wx.BoxSizer(wx.HORIZONTAL)
        self.file_ctrl = wx.TextCtrl(panel, style=wx.TE_READONLY)
        browse_btn = wx.Button(panel, label="Browse...")
        browse_btn.Bind(wx.EVT_BUTTON, self.on_browse)
        hbox1.Add(self.file_ctrl, 1, wx.EXPAND | wx.RIGHT, 4)
        hbox1.Add(browse_btn, 0)
        file_box.Add(hbox1, 0, wx.EXPAND | wx.ALL, 8)

        vbox.Add(file_box, 0, wx.EXPAND | wx.ALL, 8)

        # Options
        opts_box = wx.StaticBoxSizer(wx.StaticBox(panel, label="Step 2: Import Options"), wx.VERTICAL)

        self.chk_footprints = wx.CheckBox(panel, label="Place component footprint stubs on PCB")
        self.chk_footprints.SetValue(True)
        self.chk_nets = wx.CheckBox(panel, label="Declare all nets")
        self.chk_nets.SetValue(True)
        self.chk_notes = wx.CheckBox(panel, label="Add placement notes as silkscreen text")
        self.chk_notes.SetValue(True)
        self.chk_bom = wx.CheckBox(panel, label="Export BOM CSV alongside PCB file")
        self.chk_bom.SetValue(True)

        opts_box.Add(self.chk_footprints, 0, wx.ALL, 4)
        opts_box.Add(self.chk_nets, 0, wx.ALL, 4)
        opts_box.Add(self.chk_notes, 0, wx.ALL, 4)
        opts_box.Add(self.chk_bom, 0, wx.ALL, 4)
        vbox.Add(opts_box, 0, wx.EXPAND | wx.ALL, 8)

        # Open Web UI button
        web_box = wx.StaticBoxSizer(wx.StaticBox(panel, label="Step 3: Generate Design (if not done yet)"), wx.VERTICAL)
        web_btn = wx.Button(panel, label="🌐  Open KiCad AI Copilot Web UI")
        web_btn.Bind(wx.EVT_BUTTON, self.on_open_web)
        web_box.Add(web_btn, 0, wx.ALL, 8)
        vbox.Add(web_box, 0, wx.EXPAND | wx.ALL, 8)

        # Buttons
        vbox.Add(wx.StaticLine(panel), 0, wx.EXPAND | wx.LEFT | wx.RIGHT, 8)
        btn_sizer = wx.StdDialogButtonSizer()
        ok_btn = wx.Button(panel, wx.ID_OK, "Import Design")
        ok_btn.SetDefault()
        cancel_btn = wx.Button(panel, wx.ID_CANCEL, "Cancel")
        btn_sizer.AddButton(ok_btn)
        btn_sizer.AddButton(cancel_btn)
        btn_sizer.Realize()
        vbox.Add(btn_sizer, 0, wx.ALIGN_RIGHT | wx.ALL, 10)

        panel.SetSizer(vbox)

    def on_browse(self, event):
        dlg = wx.FileDialog(
            self, "Select AI Copilot JSON",
            wildcard="JSON files (*.json)|*.json|All files (*.*)|*.*",
            style=wx.FD_OPEN | wx.FD_FILE_MUST_EXIST
        )
        if dlg.ShowModal() == wx.ID_OK:
            self.json_path = dlg.GetPath()
            self.file_ctrl.SetValue(self.json_path)
        dlg.Destroy()

    def on_open_web(self, event):
        if WEB_UI_PATH.exists():
            webbrowser.open(WEB_UI_PATH.as_uri())
        else:
            wx.MessageBox(
                f"Web UI not found at:\n{WEB_UI_PATH}\n\nMake sure the KiCad AI Copilot folder is intact.",
                "Not Found", wx.OK | wx.ICON_WARNING
            )

    def get_options(self):
        return {
            "footprints": self.chk_footprints.IsChecked(),
            "nets": self.chk_nets.IsChecked(),
            "notes": self.chk_notes.IsChecked(),
            "bom": self.chk_bom.IsChecked(),
            "json_path": self.json_path
        }


# ═══════════════════════════════════════════════════════════
# PCB IMPORTER (KiCad 7-9 pcbnew API)
# ═══════════════════════════════════════════════════════════
class PCBImporter:
    """
    Imports AI Copilot design JSON into a live KiCad PCB
    using the pcbnew Python API.
    """

    # Grid spacing for auto-placement (mm)
    GRID_X = 15.0
    GRID_Y = 15.0
    ORIGIN_X = 10.0
    ORIGIN_Y = 10.0
    PER_ROW = 6

    def __init__(self, board: "pcbnew.BOARD", design: dict):
        self.board = board
        self.design = design
        self.log = []

    def run(self, options: dict):
        """Main import routine."""
        errors = []
        try:
            if options.get("nets"):
                self._import_nets()
            if options.get("footprints"):
                self._import_footprints()
            if options.get("notes"):
                self._add_placement_notes()
            if options.get("bom"):
                self._export_bom(options["json_path"])

            pcbnew.Refresh()
            return True, self.log

        except Exception as e:
            errors.append(str(e))
            return False, errors

    def _import_nets(self):
        """Declare all nets from the design."""
        nets = self.design.get("nets", [])
        netinfo = self.board.GetNetInfo()

        for net_data in nets:
            net_name = net_data.get("name", "")
            if not net_name:
                continue
            # Check if net already exists
            existing = netinfo.FindNet(net_name)
            if not existing:
                net = pcbnew.NETINFO_ITEM(self.board, net_name)
                self.board.Add(net)
                self.log.append(f"Net added: {net_name}")
            else:
                self.log.append(f"Net exists: {net_name}")

    def _import_footprints(self):
        """Place component footprints as stubs."""
        components = self.design.get("components", [])

        for i, comp in enumerate(components):
            col = i % self.PER_ROW
            row = i // self.PER_ROW
            x_mm = self.ORIGIN_X + col * self.GRID_X
            y_mm = self.ORIGIN_Y + row * self.GRID_Y

            fp_str = comp.get("footprint", "")
            ref = comp.get("ref", f"U{i+1}")
            val = comp.get("value", comp.get("name", "?"))

            if not fp_str:
                self.log.append(f"  SKIP {ref}: no footprint defined")
                continue

            try:
                # Load footprint from library
                # fp_str format: "Library:FootprintName"
                lib_part = fp_str.split(":")
                if len(lib_part) == 2:
                    lib_name, fp_name = lib_part
                else:
                    self.log.append(f"  SKIP {ref}: invalid footprint format '{fp_str}'")
                    continue

                fp = pcbnew.FootprintLoad(lib_name, fp_name)
                if fp is None:
                    # Create a minimal placeholder if footprint not found
                    fp = self._make_placeholder(ref, val, fp_str)
                    self.log.append(f"  PLACEHOLDER {ref} ({fp_str} not in library)")
                else:
                    self.log.append(f"  PLACED {ref}: {fp_str}")

                # Set reference and value
                fp.Reference().SetText(ref)
                fp.Value().SetText(val)

                # Position
                pos = pcbnew.VECTOR2I(
                    pcbnew.FromMM(x_mm),
                    pcbnew.FromMM(y_mm)
                )
                fp.SetPosition(pos)

                # Add component description property
                reason = comp.get("reason", "")
                if reason:
                    try:
                        fp.SetDescription(reason[:80])
                    except Exception:
                        pass

                self.board.Add(fp)

            except Exception as e:
                self.log.append(f"  ERROR {ref}: {e}")

    def _make_placeholder(self, ref: str, val: str, fp_str: str) -> "pcbnew.FOOTPRINT":
        """Create a minimal 1x1mm placeholder footprint."""
        fp = pcbnew.FOOTPRINT(self.board)
        fp.Reference().SetText(ref)
        fp.Value().SetText(val)
        fp.SetDescription(f"Placeholder: {fp_str}")

        # Add a courtyard rectangle (1mm x 1mm)
        rect = pcbnew.PCB_SHAPE(fp, pcbnew.SHAPE_T_RECT)
        rect.SetLayer(pcbnew.F_CrtYd)
        rect.SetStart(pcbnew.VECTOR2I(pcbnew.FromMM(-0.5), pcbnew.FromMM(-0.5)))
        rect.SetEnd(pcbnew.VECTOR2I(pcbnew.FromMM(0.5), pcbnew.FromMM(0.5)))
        rect.SetWidth(pcbnew.FromMM(0.05))
        fp.Add(rect)
        return fp

    def _add_placement_notes(self):
        """Add PCB placement rules as silkscreen/Eco1 text."""
        rules = self.design.get("pcb_placement_rules", [])
        rf_rules = self.design.get("rf_or_critical_rules", [])

        y_pos = 5.0
        x_pos = -60.0  # Left of board origin

        for rule in rules[:8]:
            text = pcbnew.PCB_TEXT(self.board)
            text.SetText(f"[AI] {rule['rule']}: {rule['description'][:70]}")
            text.SetPosition(pcbnew.VECTOR2I(
                pcbnew.FromMM(x_pos), pcbnew.FromMM(y_pos)
            ))
            text.SetLayer(pcbnew.Eco1_User)
            text.SetTextSize(pcbnew.VECTOR2I(pcbnew.FromMM(0.8), pcbnew.FromMM(0.8)))
            self.board.Add(text)
            y_pos += 3.5

        for rule in rf_rules[:4]:
            text = pcbnew.PCB_TEXT(self.board)
            text.SetText(f"[RF-{rule['importance'].upper()}] {rule['rule']}: {rule['description'][:60]}")
            text.SetPosition(pcbnew.VECTOR2I(
                pcbnew.FromMM(x_pos), pcbnew.FromMM(y_pos)
            ))
            text.SetLayer(pcbnew.Eco2_User)
            text.SetTextSize(pcbnew.VECTOR2I(pcbnew.FromMM(0.8), pcbnew.FromMM(0.8)))
            self.board.Add(text)
            y_pos += 3.5

        self.log.append(f"Placement notes added: {len(rules)} rules, {len(rf_rules)} RF rules")

    def _export_bom(self, json_path: str):
        """Export BOM CSV next to the PCB file."""
        import csv
        board_path = Path(self.board.GetFileName())
        if not board_path.exists():
            bom_path = Path(json_path).parent / "bom.csv"
        else:
            bom_path = board_path.parent / f"{board_path.stem}_bom.csv"

        components = self.design.get("components", [])
        auto = self.design.get("auto_added_components", [])

        with open(bom_path, "w", newline="", encoding="utf-8") as f:
            writer = csv.writer(f)
            writer.writerow(["Ref", "Name", "Value", "Type", "Footprint", "LCSC", "Reason"])
            for c in components:
                writer.writerow([c.get("ref"), c.get("name"), c.get("value"),
                                  c.get("type"), c.get("footprint"), c.get("lcsc",""), c.get("reason","")])
            writer.writerow([])
            writer.writerow(["# AUTO-ADDED"])
            for a in auto:
                writer.writerow([a.get("ref","AUTO"), a.get("name",""), a.get("value",""),
                                  "Auto", a.get("footprint",""), "", a.get("reason","")])

        self.log.append(f"BOM exported: {bom_path}")


# ═══════════════════════════════════════════════════════════
# ACTION PLUGIN (KiCad 7-9)
# ═══════════════════════════════════════════════════════════
if HAS_KICAD:
    class KiCadAICopilotAction(pcbnew.ActionPlugin):
        """
        KiCad Action Plugin for AI Copilot.
        Appears in: Tools → External Plugins → KiCad AI Copilot
        """

        def defaults(self):
            self.name = "KiCad AI Copilot"
            self.category = "EDA Automation"
            self.description = (
                "Import AI-generated PCB designs from the KiCad AI Copilot web tool. "
                "Automatically places components, declares nets, and adds PCB placement rules."
            )
            self.show_toolbar_button = True

            icon = str(ICON_PATH)
            if os.path.exists(icon):
                self.icon_file_name = icon
            else:
                self.icon_file_name = ""

        def Run(self):
            """Called when the plugin is activated from KiCad Tools menu."""
            board = pcbnew.GetBoard()
            parent = wx.FindWindowByName("PcbFrame") or None

            # Show import dialog
            dlg = CopilotImportDialog(parent)
            result = dlg.ShowModal()
            options = dlg.get_options()
            dlg.Destroy()

            if result != wx.ID_OK:
                return

            json_path = options.get("json_path")
            if not json_path:
                wx.MessageBox(
                    "No JSON file selected.\n\n"
                    "Please generate a design using the KiCad AI Copilot web tool first, "
                    "then export the JSON.",
                    "No File", wx.OK | wx.ICON_WARNING
                )
                return

            # Load JSON
            try:
                with open(json_path, "r", encoding="utf-8") as f:
                    design = json.load(f)
            except Exception as e:
                wx.MessageBox(f"Failed to read JSON:\n{e}", "Error", wx.OK | wx.ICON_ERROR)
                return

            # Run importer
            importer = PCBImporter(board, design)
            success, log = importer.run(options)

            # Show results
            log_text = "\n".join(log[:30])
            if len(log) > 30:
                log_text += f"\n... and {len(log)-30} more"

            if success:
                comp_count = len(design.get("components", []))
                auto_count = len(design.get("auto_added_components", []))
                net_count = len(design.get("nets", []))
                wx.MessageBox(
                    f"✅ Design imported successfully!\n\n"
                    f"• {comp_count} components placed\n"
                    f"• {auto_count} auto-added support components referenced\n"
                    f"• {net_count} nets declared\n"
                    f"• Placement notes added\n\n"
                    f"Log:\n{log_text}\n\n"
                    f"⚠️  Note: Support components (decoupling caps, pull-ups, etc.) "
                    f"are listed in the BOM but you must manually add them to the schematic "
                    f"and PCB using the reference list.",
                    "Import Complete", wx.OK | wx.ICON_INFORMATION
                )
            else:
                wx.MessageBox(
                    f"Import completed with errors:\n\n{log_text}",
                    "Import Warnings", wx.OK | wx.ICON_WARNING
                )
